name: Nordic skibums
favicon: null
layout_spectrum: 0.74067
typography_spectrum: 0.53465
title: Nordic skibums community and lifestyle store
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5c789d'
    - '#405d7d'
    - '#9bb4d2'
    - '#d3dee4'
    - '#152131'
  brandStrength: 0.5
  lightness: 0.42936557391658425
  saturation: 0.5
  rhythmicContrast: 0.829182913294062
purpose: []
